name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: markdownlint-cli
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: readme.md
          config_file: ".markdownlint.json"
